name: Merge dev to main

on:
  push:
    branches:
      - main
      
  schedule:
    - cron: "0 0 * * *"

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge dev to main
        run: |
          git config --global user.name 'AutoMerge'
          git config --global user.email 'AutoMerge@github.com'
          git pull --unshallow
          git checkout main
          # git merge --no-edit origin/dev
          git merge --strategy-option=theirs origin/dev
          git push origin main
