name: Merge dev to main

on:
  push:
    branches:
      - main
      
  schedule:
    - cron: "0 0 * * *"

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Merge dev to main
        run: |
          git checkout dev
          git checkout main
          git pull
          git merge dev --no-ff --no-edit
          git push origin main